- name: 设置wheel用户组 免密sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel  ALL=(ALL)       NOPASSWD: ALL'

- name: 创建sudo 用户
  ansible.builtin.user:
    name: "{{ su_username }}"
    password: "{{ su_user_passwd | password_hash('sha512') }}"
    update_password: always
    comment: "袁杨"
    group: wheel

- name: 设置root用户登陆的key
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - "{{ root_key }}"

- name: 设置sudo用户登陆的key
  authorized_key:
    user: "{{ su_username }}"
    state: present
    key: '{{ item }}'
  with_file:
    - "{{ su_user_key }}"


- block:
  - name: 更改ssh 端口
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#Port'
      line: "{{ ssh_port }}"

  - name: 关闭ssh dns反查
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#UseDNS'
      line: 'UseDNS no'

  - name: 关闭密码认证 使用key认证
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#PasswordAuthentication'
      line: "PasswordAuthentication no"
    when: disable_ssh_password == false

  - name: 禁止root登陆
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#PermitRootLogin'
      line: "PermitRootLogin no"
    when: disable_root_login  == true

  - name: restart ssh
    service:
     name=sshd
     state=restarted
