- name: 设置wheel用户组 免密sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel  ALL=(ALL)       NOPASSWD: ALL'

- name: 创建sudo 用户
  ansible.builtin.user:
    name: "{{ su_username }}"
    password: "{{ su_user_passwd | password_hash('sha512') }}"
    update_password: always
    comment: "sudoer"
    group: wheel

- name: 设置root用户登陆的key
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - "{{ root_key }}"

- name: 设置sudo用户登陆的key
  authorized_key:
    user: "{{ su_username }}"
    state: present
    key: '{{ item }}'
  with_file:
    - "{{ su_user_key }}"

- block:
  - name: 批量创建普通用户
    user:
      name: '{{ item }}'
      password: "{{ user_passwd | password_hash('sha512') }}"
      update_password: on_create
    register: user_created
    when: create_user  == "true"
    with_items:
      - '{{ user_list }}'

  - name: 强制用户登陆时更改密码
    shell: "chage -d 0 {{ item }}"
    when: user_created.changed
    with_items:
      - '{{ user_list }}'
