---
- name: 安装软件 audit
  package:
    name: '{{ auditd_package }}'
    state: 'present'
  tags: auditd

- name: 配置 audit
  template:
    src: 'etc/audit/auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
    backup: yes
  notify: 'restart-auditd'
  tags: auditd
