---
- block:
  - name: 创建文件夹 /etc/security/limits.d  如果不存在
    file:
      path: '/etc/security/limits.d'
      owner: 'root'
      group: 'root'
      mode: '0755'
      state: 'directory'

  - name: 创建文件10.hardcore.conf
    pam_limits:
      dest: '/etc/security/limits.d/10.hardcore.conf'
      domain: '*'
      limit_type: hard
      limit_item: core
      value: '0'
      comment: Prevent core dumps for all users. These are usually not needed and may contain sensitive information

  - name: 设置/etc/security/limits.d/10.hardcore.conf 文件权限
    file:
      path: /etc/security/limits.d/10.hardcore.conf
      owner: 'root'
      group: 'root'
      mode: '0440'
      state: touch
      modification_time: preserve
      access_time: preserve

  when: not os_security_kernel_enable_core_dump | bool

- name: 删除/etc/security/limits.d/10.hardcore.conf
  file:
    path: /etc/security/limits.d/10.hardcore.conf
    state: absent
  when: os_security_kernel_enable_core_dump | bool
