---
- name: 安装 sssd-clients
  yum:
    name: sssd-client
    state: 'present'
  when:
    - os_auth_pam_sssd_enable | bool

- name: 配置 /etc/pam.d/system-auth-local
  template:
    src: 'etc/pam.d/rhel_auth.j2'
    dest: '/etc/pam.d/system-auth-local'
    mode: '0640'
    owner: 'root'
    group: 'root'

- name:  开启我们配置的system-auth
  file:
    src: /etc/pam.d/system-auth-local
    dest: /etc/pam.d/system-auth
    mode: '0640'
    owner: 'root'
    group: 'root'
    state: link
    force: true

- name: 配置 /etc/pam.d/password-auth-local
  template:
    src: 'etc/pam.d/rhel_auth.j2'
    dest: '/etc/pam.d/password-auth-local'
    mode: '0640'
    owner: 'root'
    group: 'root'

- name: 开启我们配置的 password-auth
  file:
    src: /etc/pam.d/password-auth-local
    dest: /etc/pam.d/password-auth
    mode: '0640'
    owner: 'root'
    group: 'root'
    state: link
    force: true
