
- block:
    - name: 准备docker相关目录
      file: name={{ item }} state=directory
      with_items:
      - /etc/docker


    - name: 下载 docker 二进制文件(19.03.14)
      copy: src=bin/{{ item }} dest=/usr/bin/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - docker-init
      - runc
      - docker
      - ctr
      - dockerd
      - docker-proxy
      - node_exporter
      - docker-compose
      tags: upgrade_docker, download_docker

    - name: docker命令自动补全
      copy: src=docker dest=/etc/bash_completion.d/docker mode=0644

    - name: docker国内镜像加速
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json

    - name: flush-iptables
      shell: "iptables -P INPUT ACCEPT \
            && iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle"

    - name: 创建docker的systemd unit文件
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker

    - name: 开机启用docker 服务
      shell: systemctl enable docker
      ignore_errors: true

    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    ## 可选 ------安装docker查询镜像 tag的小工具----
    # 先要安装轻量JSON处理程序‘jq’，已在 prepare 节点安装
    - name: 下载 docker-tag
      copy: src=docker-tag dest=/usr/bin/docker-tag mode=0755

    - name: 轮询等待docker服务运行
      shell: "systemctl status docker.service|grep Active"
      register: docker_status
      until: '"running" in docker_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade_docker

- block:

    - name: 创建node_exporter的systemd unit文件
      template: src=node_exporter.service dest=/etc/systemd/system/node_exporter.service
      tags: node_exporter
      when: ENABLE_NODE_EXPORTTER == "true"

    - name: node_exporter 配置文件
      copy: src=sysconfig.node_exporter dest=/etc/sysconfig/node_exporter mode=0644
      when: ENABLE_NODE_EXPORTTER == "true"
      tags: node_exporter

    - name: 开机启用 node_exporter 服务
      shell: systemctl enable node_exporter
      ignore_errors: true
      tags: node_exporter
      when: ENABLE_NODE_EXPORTTER == "true"

    - name: 开启 node_exporter 服务
      shell: systemctl daemon-reload && systemctl restart node_exporter
      tags: node_exporter
      when: ENABLE_NODE_EXPORTTER == "true"
