- name: 删除centos/redhat默认安装
  yum: 
    name: 
      - firewalld
      - python-firewall
      - firewalld-filesystem
    state: absent

- name: 更改yum为阿里云 centos7 镜像
  ansible.builtin.copy:
    src: centos7_yum.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: ansible_distribution_major_version == "7"

- name: 更改yum为阿里云 centos8 镜像
  ansible.builtin.copy:
    src: centos8_yum.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: ansible_distribution_major_version == "8"



- name: 安装基础软件包
  yum: 
    name: 
      - conntrack-tools     # ipvs 模式需要
      - psmisc        # 安装psmisc 才能使用命令killall，它在keepalive的监测脚本中使用到
      - nfs-utils     # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
      - socat               # 用于port forwarding
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - rsync               # 文件同步工具，分发证书等配置文件需要
      - ipset
      - ipvsadm
      - ntpdate
      - lrzsz
      - lvm2
      - tmux
      - wget
      - xfsprogs
      - atop
      - iotop
      - htop
      - iftop
      - nfs-utils
      - MySQL-python
      - crontabs
      - daemonize
      - nc
      - telnet
      - sysstat
      - jnettop
      - python-pip
      - oddjob-mkhomedir
      - zlib-devel
      - openssl-devel
    state: latest

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: 禁止rsyslog获取journald日志
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'ModLoad imjournal'
    line: '#$ModLoad imjournal # provides access to the systemd journal'

- name: 重启rsyslog服务
  service: name=rsyslog state=restarted
