- name: 删除centos/redhat默认安装
  yum: 
    name: 
      - firewalld #卸载firewalld 使用iptables-services
      - python-firewall
      - firewalld-filesystem
      - ntp #卸载ntp 使用 chrony
    state: absent

- name: 更改yum为阿里云 centos7 镜像
  ansible.builtin.copy:
    src: centos7_yum.repo/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: ansible_distribution_major_version == "7"


- name: 更改yum为阿里云 centos8 镜像
  ansible.builtin.copy:
    src: centos8_yum.repo/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: ansible_distribution_major_version == "8"

- block:
  - name: 配置使 resolv.conf 重启依旧生效
    lineinfile:
       dest: /etc/NetworkManager/NetworkManager.conf
  #     regexp: '^local2'
  #     insertafter: "[main]"
       insertbefore: "^#plugin"
       line: "dns=none"
  - name: 重启 NetworkManager 服务
    service: name=NetworkManager state=restarted

  - name: 设置默认dns地址
    template: src=resolv.conf.j2 dest=/etc/resolv.conf



- name: 清理yum 缓存
  shell: " yum clean all && yum makecache fast"
  args:
    warn: no

- name: 统一字符集
  lineinfile:
    dest: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG="en_US.UTF-8"'

- name: 安装基础软件包7
  yum: 
    name:
      - "{{ item }}"
    state: latest
  with_items:
    - "{{ centos7_pkgs }}"
  when: ansible_distribution_major_version == "7"

- name: 安装基础软件包8
  yum:
    name:
      - "{{ item }}"
    state: latest
  with_items:
    - "{{ centos8_pkgs }}"
  when: ansible_distribution_major_version == "8"

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 记录用户操作命令 及 设置 history 上限
  ansible.builtin.copy:
    src: user_cmd.sh
    dest: /etc/profile.d/user_cmd.sh

- name: 设置终端超时时间
  lineinfile:
    dest: /etc/profile.d/user_cmd.sh
    line: "{{ cmd_timeout }}"

- name: 设置时区
  file:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
    state: link


- block:
    - name: 添加记录操作日志 rsyslog配置
      lineinfile:
         dest: /etc/rsyslog.conf
         insertbefore: '^local7'
         line: 'local2.*                                                /var/log/cmd-line.log'

    - name: Show debug info
      debug: var=enable_rsyslog_to_mysql verbosity=0

    - name: 安装 rsyslog-mysql
      yum:
        name:
          - "rsyslog-mysql"
        state: latest
      when: enable_rsyslog_to_mysql == "true"

    - name: 设置日志存入到mysql的模块
      lineinfile:
        dest: /etc/rsyslog.conf
        line: "$ModLoad ommysql"
      when: enable_rsyslog_to_mysql == "true"

    - name: 设置日志存入数据库连接信息
      lineinfile:
        dest: /etc/rsyslog.conf
        line: "{{ rsyslog_mysql }}"
      when: enable_rsyslog_to_mysql == "true"

    - name: 重启rsyslog服务
      service: name=rsyslog state=restarted

- block:
    - name: 配置 chrony client
      template: src=client-centos.conf.j2 dest=/etc/chrony.conf
      when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"

    - name: 启动 chrony client
      service: name=chronyd state=restarted enabled=yes
      when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"
